version: '3.8'

services:
  server1:
    build: ./server01
    stdin_open: true
    tty: true
    ports: 
      - 5040:5040
    networks:
      - pub-sub-distributed-rendezvous
    container_name: server001

  server2:
    build: ./server02
    stdin_open: true
    tty: true
    ports: 
      - 5041:5041
    networks:
      - pub-sub-distributed-rendezvous
    depends_on:
      - server1
    container_name: server002

  server3:
    build: ./server03
    stdin_open: true
    tty: true
    ports: 
      - 5043:5043
    networks:
      - pub-sub-distributed-rendezvous
    depends_on:
      - server2
    container_name: server003

  client1:
    build: ./client01
    stdin_open: true
    tty: true    
    networks:
      - pub-sub-distributed-rendezvous
    depends_on:
      - server1
    container_name: client001

  client2:
    build: ./client02
    stdin_open: true
    tty: true    
    networks:
      - pub-sub-distributed-rendezvous
    depends_on:
      - server2
    container_name: client002

  client3:
    build: ./client03
    stdin_open: true
    tty: true    
    networks:
      - pub-sub-distributed-rendezvous
    depends_on:
      - server3
    container_name: client003

networks:
  pub-sub-distributed-rendezvous:
    driver: bridge

