FROM nginx:alpine
COPY . /usr/share/nginx/html

#This Dockerfile instruction copies all files from the current directory (the build context) into the "/usr/share/nginx/html" directory of the NGINX container based on the "nginx:alpine" image.