FROM python:3.6.4-slim
COPY . /client02
CMD ["python","/client02/client2.py","c-subscriber_02"]
EXPOSE 5000
#This Dockerfile builds an image based on Python 3.6.4-slim, copies the contents of the current directory to the /client02 directory in the image, sets the command to run "python /client02/client2.py c-subscriber_02" when a container is started, and exposes port 5000.



